#!/usr/bin/env bash
# duplicate web-01 to web-02
# these scripts are an upgrade from the web-server scripts...

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Configure Nginx to add custom HTTP response header
sudo sed -i '/http {/a \        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart

