#!/usr/bin/env bash
# install load balancer

# Update package repositories
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Verify HAProxy installation
if [ $(dpkg-query -W -f='${Status}' haproxy 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo "HAProxy installation failed. Exiting."
    exit 1
fi

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Define HAProxy configuration
haproxy_config="
defaults
    timeout client 30s
    timeout server 30s
    timeout connect 5s

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    timeout server 30s
    server 437972-web-01 100.26.217.232:80 check
    server 437972-web-02 3.85.196.97:80 check
"

# Write HAProxy configuration to file
echo "$haproxy_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to be managed via init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy
sudo service haproxy restart

# Verify HAProxy status
sudo service haproxy status
