#!/usr/bin/env bash
# Create MySQL server backup

# Check if the password argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# MySQL dump filename
backup_file="backup.sql"

# Compressed archive filename
archive_file="$(date +'%d-%m-%Y').tar.gz"

# MySQL dump command
mysqldump -u root -p"$1" --all-databases > "$backup_file"

# Check if mysqldump command was successful
if [ $? -ne 0 ]; then
    echo "MySQL dump failed. Exiting..."
    exit 1
fi

# Create compressed archive
tar -czvf "$archive_file" "$backup_file"

# Check if tar command was successful
if [ $? -ne 0 ]; then
    echo "Creating archive failed. Exiting..."
    exit 1
fi

echo "Backup completed: $archive_file"

